module NSWE
	EAST  = 1 << 0
	WEST  = 1 << 1
	SOUTH = 1 << 2
	NORTH = 1 << 3

	NORTH_EAST = NORTH | EAST
	NORTH_WEST = NORTH | WEST
	SOUTH_EAST = SOUTH | EAST
	SOUTH_WEST = SOUTH | WEST

	ALL = EAST | WEST | SOUTH | NORTH
end
