enum PcCondOverride : UInt8
  MAX_STATS_VALUE
  ITEM_CONDITIONS
  SKILL_CONDITIONS
  ZONE_CONDITIONS
  CASTLE_CONDITIONS
  FORTRESS_CONDITIONS
  CLANHALL_CONDITIONS
  FLOOD_CONDITIONS
  CHAT_CONDITIONS
  INSTANCE_CONDITIONS
  QUEST_CONDITIONS
  DEATH_PENALTY
  DESTROY_ALL_ITEMS
  SEE_ALL_PLAYERS
  TARGET_ALL
  DROP_ALL_ITEMS
end
