class TraitType < EnumClass
  getter type

  protected initializer type : UInt8

  add(NONE, 0)
  add(SWORD, 1)
  add(BLUNT, 1)
  add(DAGGER, 1)
  add(POLE, 1)
  add(FIST, 1)
  add(BOW, 1)
  add(ETC, 1)
  add(UNK_8, 0)
  add(POISON, 3)
  add(HOLD, 3)
  add(BLEED, 3)
  add(SLEEP, 3)
  add(SHOCK, 3)
  add(DERANGEMENT, 3)
  add(BUG_WEAKNESS, 2)
  add(ANIMAL_WEAKNESS, 2)
  add(PLANT_WEAKNESS, 2)
  add(BEAST_WEAKNESS, 2)
  add(DRAGON_WEAKNESS, 2)
  add(PARALYZE, 3)
  add(DUAL, 1)
  add(DUALFIST, 1)
  add(BOSS, 3)
  add(GIANT_WEAKNESS, 2)
  add(CONSTRUCT_WEAKNESS, 2)
  add(DEATH, 3)
  add(VALAKAS, 2)
  add(ANESTHESIA, 2)
  add(CRITICAL_POISON, 3)
  add(ROOT_PHYSICALLY, 3)
  add(ROOT_MAGICALLY, 3)
  add(RAPIER, 1)
  add(CROSSBOW, 1)
  add(ANCIENTSWORD, 1)
  add(TURN_STONE, 3)
  add(GUST, 3)
  add(PHYSICAL_BLOCKADE, 3)
  add(TARGET, 3)
  add(PHYSICAL_WEAKNESS, 3)
  add(MAGICAL_WEAKNESS, 3)
  add(DUALDAGGER, 1)
  add(DEMONIC_WEAKNESS, 2) # CT26_P4
  add(DIVINE_WEAKNESS, 2)
  add(ELEMENTAL_WEAKNESS, 2)
  add(FAIRY_WEAKNESS, 2)
  add(HUMAN_WEAKNESS, 2)
  add(HUMANOID_WEAKNESS, 2)
  add(UNDEAD_WEAKNESS, 2)
end
