struct CharFlags < AbstractFlags
  flags(
    "invul",
    "mortal",
    "dead",
    "paralyzed",
    "immobilized",
    "lethalable",
    "overloaded",
    "running",
    "flying",
    "teleporting",
    "pending_revive",
    "no_random_walk",
    "show_summon_animation",
    "all_skills_disabled",
    "core_ai_disabled",
    "casting_now",
    "casting_simultaneously_now"
  )
end
